# -*- coding: utf-8 -*-
"""EEL4810 - AudioClassificationProj

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LxjhDjwRZIZC3sz8Jh9b7xY_2AAtJppA
"""



"""#Pipeline for Enviromental Audio Classification using Custom CNN Pipeline"""

# Import Neccesary Libraries
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torchaudio.transforms as spec
from torch.utils.data import DataLoader, TensorDataset
from torch.utils.data import Dataset
import torch.nn.functional as F
import matplotlib.pyplot as plt
import pandas as pd

# Check and set device to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"PyTorch version : {torch.__version__}")
print(f"Device          : {device}")
if device.type == "cuda":
    print(f"GPU             : {torch.cuda.get_device_name(0)}")

# Import dataset from HuggingFace
from datasets import load_dataset
audio_dataset = load_dataset("ashraq/esc50")

# Split dataset into training / validation / testing datasets
# Calculate index splits based on 70 / 15 / 15 ssample splits
total_samples = int(len(audio_dataset["train"]))
train_end = int(0.70 * total_samples)
val_end   = int(0.85 * total_samples)

# Split the datasets accordingly
total_set = audio_dataset["train"].shuffle(seed=42)
training_dataset = total_set.select(range(train_end))
validation_dataset   = total_set.select(range(train_end, val_end))
testing_dataset  = total_set.select(range(val_end, total_samples))

# Verify size of split datasets
print("No. of Training Samples: " + str(len(training_dataset)))
print("No. of Validation Samples: " + str(len(validation_dataset)))
print("No. of Testing Samples: " + str(len(testing_dataset)))

# Example metadata extraction
print(total_set)
print("\n")
def metadata_extraction(sample):
  print("Filename: " + sample["filename"])
  print("K-Fold F: " + str(sample["fold"]))
  print("Target Class (y_hat): " + str(sample["target"]))
  print("Class (in english): " + sample["category"])
  print("metadata: " + str(sample["src_file"]))
  print("metadata: " + str(sample["take"]))
  print("Audio Features: ")
  print(sample["audio"]["array"])

metadata_extraction(training_dataset[0])

# Create PyTorch Datasets
class ESC50TorchDataset(torch.utils.data.Dataset):
    def __init__(self, hf_dataset):
        self.ds = hf_dataset
        self.mel_spec = spec.MelSpectrogram( # convert to spectrogram (parameters are subject to change)
            sample_rate=44100,
            n_fft=1024,
            hop_length=512,
            n_mels=128
        )

    def __len__(self):
        return len(self.ds)

    def __getitem__(self, idx):
        sample = self.ds[idx]
        waveform = torch.tensor(sample["audio"]["array"], dtype=torch.float32) # torch tensor conversion
        if waveform.ndim == 1:
            waveform = waveform.unsqueeze(0)
        mel_spec = self.mel_spec(waveform) # convert to spectrogram
        mel_spec = torch.log(mel_spec + 1e-9)
        target = torch.tensor(sample["target"], dtype=torch.long)

        return mel_spec, target

train_torch_dataset = ESC50TorchDataset(training_dataset)
val_torch_dataset = ESC50TorchDataset(validation_dataset)
test_torch_dataset = ESC50TorchDataset(testing_dataset)

# Tesinting  how the the spectrogram images turned out
x, y = train_torch_dataset[132]
#print(x)
#print(x.shape)
#print(y)

mel_spec = x[-1].numpy()
print(x.shape)


plt.figure()
plt.imshow(mel_spec, aspect='auto', origin='lower')
plt.title(f"Mel Spectrogram (Label: {y})")
plt.xlabel("Time")
plt.colorbar()
plt.show()

# Dataloader(s)
training_loader = DataLoader(
    dataset=train_torch_dataset,
    batch_size=64,
    shuffle=True
)

validation_loader = DataLoader(
    dataset=val_torch_dataset,
    batch_size=64,
    shuffle=True #maybe change idk if validation is shuffled or not
)

test_loader = DataLoader(
    dataset=test_torch_dataset,
    batch_size=64,
    shuffle=False
)

class CNN(nn.Module):
    def __init__(self, num_classes):
        super(CNN, self).__init__()
        # Input after padding: 1 x 448 x 128
        self.conv1 = nn.Conv2d(1, 16, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, stride=2, padding=1)   # 448x128 -> 224x64

        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
        self.conv4 = nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1)  # 224x64 -> 112x32

        self.conv5 = nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1)
        self.conv6 = nn.Conv2d(128, 256, kernel_size=3, stride=2, padding=1) # 112x32 -> 56x16

        self.conv7 = nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1)
        self.conv8 = nn.Conv2d(256, 256, kernel_size=3, stride=2, padding=1) # 56x16 -> 28x8

        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc1 = nn.Linear(256, 128)
        self.fc2 = nn.Linear(128, num_classes)

        self.dropout = nn.Dropout(0.5)

    def forward(self, x):
        x = F.pad(x, (8,9,0,0), mode='replicate') # Add padding so spectr. is div by power of 2
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))

        x = F.relu(self.conv3(x))
        x = F.relu(self.conv4(x))

        x = F.relu(self.conv5(x))
        x = F.relu(self.conv6(x))

        x = F.relu(self.conv7(x))
        x = F.relu(self.conv8(x))

        x = self.global_pool(x)          # N x 256 x 1 x 1
        x = torch.flatten(x, 1)          # N x 256

        x = self.dropout(F.relu(self.fc1(x)))
        x = self.fc2(x)

        return x

# Hyperparameters
learning_rate = 0.0001
epochs = 500
num_classes = 50

model = CNN(num_classes).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate, weight_decay=1e-4)

# Training Loop
for epoch in range(epochs):
    # ===== TRAINING =====
    model.train()

    running_loss = 0.0
    correct = 0
    total = 0

    for batch_idx, (data, targets) in enumerate(training_loader):
        data = data.to(device)
        targets = targets.to(device)

        # Forward pass
        outputs = model(data)
        loss = criterion(outputs, targets)

        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Metrics
        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        correct += (predicted == targets).sum().item()
        total += targets.size(0)

    train_loss = running_loss / len(training_loader)
    train_acc = 100 * correct / total

    # ===== VALIDATION =====
    model.eval()

    val_correct = 0
    val_total = 0
    val_loss = 0.0

    with torch.no_grad():
        for data, targets in validation_loader:
            data = data.to(device)
            targets = targets.to(device)

            outputs = model(data)
            loss = criterion(outputs, targets)

            val_loss += loss.item()

            _, predicted = torch.max(outputs, 1)
            val_correct += (predicted == targets).sum().item()
            val_total += targets.size(0)

    val_loss /= len(validation_loader)
    val_acc = 100 * val_correct / val_total

    # ===== PRINT =====
    print(
        f'Epoch [{epoch+1}/{epochs}] | '
        f'Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}% | '
        f'Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.2f}%'
    )